### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tycode** [creationix/node-sdl#11]
What license is node-sdl released under? I can't seem to find one in any files.

**Comment by Freezerburn** [comment]
What would be a good license to put this under? My default inclination is to use MIT. I'll ask @creationix about if he has any preferences about this.

**Comment by creationix** [comment]
MIT is fine.  For larger projects I use Apache since it has some patent
clauses.  But almost all my JS libraries are MIT.

**Comment by Freezerburn** [comment]
MIT license text has been added to README.md as well as a new LICENSE.txt file. This should probably be put at the top of all source files as well, and I will work on doing that at some point.

**Comment by creationix** [comment]
Personally, I think putting the license at the top of every file is going a
bit overboard, but I'm not a lawyer, I'm an engineer.  My feelings are that
if you care enough to put the license on every file, then perhaps you
should use a better license than MIT (like Apache).

MIT to me means that I don't care what you do with this code, I don't care
about legal status and I'm doing the minimal work to license it.  Just my
opinion, you're free to do what you want as long as it stays an open
license like MIT or Apache.

**Comment by Freezerburn** [comment]
@creationix  That's fair enough. I was mostly just imitating what most open source projects tend to do. (such as SDL, since I've been looking at their source) They have a copy of their license at the top of every source file, hence why I was planning on doing the same. It isn't too much work to do that, so I figured I might as well.

**Comment by creationix** [comment]
Like I said, I'm not a lawyer and I don't have strong feelings.  All I ask
is that if you do add a license to every file, at least find out why they
do it and don't blindly add it just because.

There is probably a very good legal reason and I haven't been bothered
enough to find out.  But part of me fears that there is no good reason and
we just go around copying what everyone else does.  To me having a massive
legal document at the top of every source file is extremely annoying and
slows my productivity.  I want to make sure that this cost is justified
before doing it.

**Comment by Freezerburn** [comment]
@creationix I just emailed one of the libSDL people about the reason for having a license at the top of every source file. I'll hold off on doing anything more with the license until I hear back from them. Seems like the best way to proceed :)
